# GitHub Actions Pipeline
name: 'yoyoCICD'

on:
  pull_request:
   branches:
      - main
   paths:
      - yoyo/**
      - tests/**
      - .github/workflows/**

  push: # if push to main is not disabled
   branches:
      - main
   paths:
      - yoyo/**
      - tests/**
      - .github/workflows/**

# Repo Permissions
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  Test:
    runs-on: 'ubuntu-latest'

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Upgrade package manager
      run: python -m pip install -U pip

    # Install dependencies        
    - name: install testing libraries
      run: pip install pytest mock codecov pydocstyle pytest-cov pylint pylint_junit

    - name: install project dependencies
      run: python -m packages.sync

    # Run tests
    - name: Run tests
      run: pytest -v tests/ --doctest-modules --junitxml=unit-testresults.xml --cov=yoyo/ --cov-append --cov-report=xml:xmlcov --cov-report=html:htmlcov 

    - name: Publish test reuslts
      uses: EnricoMi/publish-unit-test-result-action@v1.37
  
    
  Build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2 

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' 

    # Install dependencies
    - name: Upgrade pip
      run: python -m pip install -U pip

    - name: Install build dependencies
      run: pip install build setuptools 

    - name: install project dependencies
      run: python -m packages.sync

    # Build
    - name: Build distribution
      run: python -m build --wheel 

    # Publish artifacts
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        tag: current-build
        allowUpdates: true
        replacesArtifacts: true

